[package]
name = "rafka-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.216", features = ["derive"] }
bincode = "1.3.3"
tokio = { version = "1.42.0", features = ["full"] }
bytes = "1.9.0"
anyhow = "1.0.95"
